steps:
    # build the container image using doccker
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA",
        "."
      ]

  # push built image to the container registry
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
      ]

  # start the image in cloud run
  # https://cloud.google.com/sdk/gcloud/reference/run/deploy
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$REPO_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--timeout",
        "300",
        "--cpu",
        "1",
        "--memory",
        "1Gi",
        "--update-env-vars",
        "SERVICE=$REPO_NAME,PROJECT_NAME=$PROJECT_ID,PROJECT_NUMBER=$PROJECT_NUMBER;CATALOG_NAME=tarchia;"
      ]