name: Regression Suite

on: [push, pull_request]

jobs:
  regression_tests:
    name: Regression Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ./
  
      - name: Set Up Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
        
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest coverage
          python -m pip install -r ./requirements.txt
          python -m pip install -r ./tests/requirements.txt

      - name: Run Regression Tests
        run: coverage run -m pytest --color=yes

      - name: Check Coverage
        run: coverage report --include=tarchia/* --fail-under=50 -m
