name: Static Analysis
on: [push]

jobs:
  bandit:
    name: Bandit Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set Up Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade bandit

      - name: Execute Test
        run: bandit -r tarchia


  mypy:
    name: Type Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set Up Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip mypy
          pip install -r $GITHUB_WORKSPACE/tests/requirements.txt

      - name: Execute Test
        run: mypy --ignore-missing-imports --python-version 3.10 --no-strict-optional mabel
  